### ISSUE TITLE
Unable to paste/enter floating point numbers into Transform window entry boxes

### ISSUE THREAD

**Issue by gateshian** [febiosoftware/FEBioStudio#1]
When opening the Edit->Transform... window, it is not possible to paste values from the clipboard into the entry boxes, unless the pasted content matches the type of number already in that box. So pasting any large integer over '0' works, but pasting a floating point number over '0' does not work. Pasting a floating point number over another floating point number that has less than three decimal places only works if the clipboard value has the same or fewer decimal places as the value already in the box.

Typing a floating point number in an entry box that contains an integer number only allows entering numbers to within 3 decimal places.

**Comment by SteveMaas1978** [comment]
I am not able to reproduce the copy/paste issue on Windows, but the precision issue was due to a hard-coded value. That should be fixed now. Let me know if that also fixed the copy/paste issue.

**Comment by gateshian** [comment]
Thanks, that resolved all the issues.
