### ISSUE TITLE
the forum registration, login, and help pages don't work and I've waited nearly two months without receiving a reply

### ISSUE THREAD

**Issue by dollPrincess** [febiosoftware/FEBioStudio#102]
Hello~ 
I'm very sorry to raise this query here but really can't get in touch with the administrator in charge of the forum. 
Despite the contact email address of "" left on the forum promising a reply within two working days, I've sent numerous emails from a number of different mails address but **have waited nearly two months without receiving a reply.**

I'm asking why the forum registration, login, and help pages don't work. Something is wrong with your forum website!  O(> V <)O Could you please check why these happened as soon as possible? 
In an urgent! urgent! 

**Problem:**

1. I can't use my account to log in. After waitting for more than 20 minutes, the log in and sign up window,which is on the right top of the FEBio forum, always show that it's loading and still it's loading. Sign up also doesn't work. Whatever I tried, the page that the forum website linked to is always the same, with the "register" button black and bold but no response after clicking.

2. the help pages in the forum website don't open  ,and don't response to mouse clicking to the page I want to see.

-----------------------------------------------------------------------------

I tried to F5 the forum website for the 2 problems above, and yes no success.

Could you exam your forum website and figure out why these happened? And connect me as soon as possible?
I am in a rush and eagerly looking forward to your yoour reply as soon as possible. 
It TRUELY bring me a big unconvinence.

Sincerely,
a user from FEBio forum website

![q1](https://github.com/user-attachments/assets/52527f92-1f55-4075-bab9-8dcc7a635ead)
![q2](https://github.com/user-attachments/assets/b43bf401-8f61-4fd3-8f1e-675c8718ce6e)

**Comment by SteveMaas1978** [comment]
Hi, 

For future reference, for general questions or problems you can reach out to info@febio.org. 

If you can tell me the username that you registered with on the forum, I will take a look and see what I can do.

Thanks,

Steve

**Comment by SteveMaas1978** [comment]
OP has reached out to info@febio.org for further assistance.
