### ISSUE TITLE
Issue: 🐛Bug report | Mesh Inspector hidden element visualization

### ISSUE THREAD

**Issue by stevenlabelle** [febiosoftware/FEBioStudio#107]
Description: The mesh inspector does not properly visualize objects when elements are hidden. The result depends on the method used to hide elements. Elements hidden by manual selection become black. When hiding elements with a plane cut, unhidden elements become black.
Version: Dev version 2.7.0.fe45f172b

To reproduce:

1. Open an model with a meshed part.
2. Hide some elements (tested by 1) manually selecting top surface elements or 2) plane cut).
3. Open the mesh inspector and visualize a data field (e.g., mesh data or Element Volume).

![image](https://github.com/user-attachments/assets/91d3bf96-fca2-4310-bb72-b7638739c0fb)

**Comment by SteveMaas1978** [comment]
Hi Steven,

This should be fixed now. Please give it another try with the latest dev version and let me know. 

Thanks,

Steve

**Comment by stevenlabelle** [comment]
This works now. Thanks.
