### ISSUE TITLE
Issue: 🙏 Feature request | Include/Exclude model sections in .feb generation

### ISSUE THREAD

**Issue by stevenlabelle** [febiosoftware/FEBioStudio#108]
Request to add the ability to include/exclude various model sections when generating the .feb file. 
Alternatively, ability to split the .feb into multiple files and reference dependencies with the "from=" mechanism.

Example: When models have large meshes and mesh data, users may wish to exclude the <Mesh> and <MeshData> sections to allow easier manipulation of the primary model components and file sharing.

**Comment by SteveMaas1978** [comment]
Hi Steven,

You can already do this. When you export an FEBio file, click the "More" button to see of all the sections will be exported. You can uncheck the sections you don't want to export. Please give that a try and let me know if this is what you had in mind.

Best,

Steve
