### ISSUE TITLE
Stuck on Welcome Page [MacOs]

### ISSUE THREAD

**Issue by david-jiang-bme** [febiosoftware/FEBioStudio#118]
Brief: After launching FEBioStudio, I am stuck on the "Welcome Page", and unable to create a new model file.

I have used FEBioStudio for many years with no issues on my MacBook Pro (Apple M1 Pro, 16GB, Sonoma 14.5). Recently, I imported a 3D image to visualize in FEBioStudio, but after a crash, I was unable to create a new model or even open an existing one (locally or from the repository). A new tab opens, but nothing appears in the graphic viewer, and the "Welcome page" remains stuck. I am, however, able to open and view .*xplt files. I have re-installed FEBio and restarted my computer many times and this issue persists.
<img width="388" alt="Screenshot 2024-10-18 at 3 12 32 PM" src="https://github.com/user-attachments/assets/db56cb0a-26ff-4599-b4cf-a95ad880d0e1">

**Comment by michaelrossherron** [comment]
David, 

We've had a few users report this problem, but we've been unable to replicate it, or figure out what's causing it. However, something you said might help us. From your description of the problem, it sounds like the software was working correctly up until it crashed, and then, only after that crash, it started to exhibit this behavior. Is that the case?

If so, then that gives us something to go off of. The fact that this worked at all on your machine is good news. If you've re-installed FEBio Studio, and it still hasn't fixed the problem, then I've got an idea that might help. Make sure that FEBio Studio is completely closed on your machine, and then open a terminal and run the following command:

`rm $HOME/Library/Preferences/com.mrlsoftware.FEBio\ Studio.plist`

After running that command, reopen FEBio Studio, and try to open a model. If that still doesn't work, then uninstall FEBio Studio, re-run that command from above, and then reinstall FEBio Studio, and see if that helps. 

Please let me know how this goes. 

Thanks,

Michael Herron

**Comment by david-jiang-bme** [comment]
Hi Michael,

I have tried the steps you described, and I cannot fix the problem. I even tried uninstalling FEBio, running the command above, and restarting my Mac. Let me know what else I can do to help.

**Comment by michaelrossherron** [comment]
Shoot. I was hoping that would help. Could you try another thing for me? Make sure that FEBio Studio is closed, and then launch it from the terminal using the `-reset` flag. You should just be able to run the following in your terminal: `FEBioStudio -reset`

Let me know if that works. 

Also, was I correct in my understanding of the issue? The same version of FEBio Studio worked on this same computer, with the same operating system, and then after crashing once, it stopped working? Is that the case?

Thanks,

Michael Herron

**Comment by david-jiang-bme** [comment]
Hi Michael,

Unfortunately, that did not fix the problem. To answer your original question, Yes, I successfully used FEBioStudio 2.7.0 on this Mac with the same OS, and then, after crashing, it started to exhibit this problem. I'm unable to update FEBioStudio to the development version as well. I've attached a screenshot from my terminal in hopes that any info may be helpful to you.

<img width="1011" alt="Screenshot 2024-10-22 at 7 17 51 PM" src="https://github.com/user-attachments/assets/7157197c-1b52-4fd7-b43f-ce8fd7943964">

Additionally, I'm able to access the model and build windows by first opening a *.xplt file, then selecting View>Windows>Model/Build, creating a primitive object, then zooming to the selection, to finally land on the graphics viewer. However, I'm still unable to open the "Preferences..." window, or as soon as I click back the *.xplt file, I'm stuck as before.

**Comment by michaelrossherron** [comment]
Thanks for the info! Could you do me another favor? Could you please download version 2.5 of FEBio Studio from [our downloads](https://febio.org/downloads/) page (click the Previous Versions link to see the older downloads), install it, and see if that version also has this problem on your machine?

Thanks!

Michael Herron

**Comment by david-jiang-bme** [comment]
Hi Michael,

I just installed version 2.5, and I have encountered NO problems on my machine. So it's specific to version 2.7.

**Comment by michaelrossherron** [comment]
Thank you for testing that out for me! I have been looking further into this issue, and I think that I may have come up with a solution. However, since I'm unable to replicate the bug, I can't test to see if it's been fixed. 

Could you test this out for me please? First uninstall any versions of FEBio Studio that you may have installed, then download a new installer that I've prepared for you from [this link](https://repo.febio.org/download/FEBioStudio_2.7_FEBio_4.7_macOS_installer.zip), install it, and test it out for me. 

Thanks!

Michael Herron

**Comment by michaelrossherron** [comment]
I've received confirmation from another user with this issue that the new installer I created solved this for them. I'm going to close this issue as resolved. If you find that this new installer does not solve the issue for you, please feel free to reopen it. 

Michael Herron
