### ISSUE TITLE
I don't know what had happened? Suddenly, errors occured

### ISSUE THREAD

**Issue by dollPrincess** [febiosoftware/FEBioStudio#121]
It was working fine before, but now cmake has started reporting that it can't find the glew library. I didn't do anything to remove or update it, the only thing I did was open a new project in clion for the msys environment and then shut him down, and this is what happened.

Obviously the glew library had been installed before and cmake was running normally, but suddenly it showed an error report. And the error is very strange, as follows:

`-- Found OpenGL: opengl32   
CMake Error at D:/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GLEW (missing: GLEW_LIBRARIES) (found version "2.2.0")
Call Stack (most recent call first):
  D:/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  D:/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/FindGLEW.cmake:242 (find_package_handle_standard_args)
  FindDependencies.cmake:638 (find_package)
  CMakeLists.txt:94 (include)`

I really don't know what's going on, do you know what to do?
 I'm **in a hurry** to use this, have you ever encountered this situation before, and what is the feasible solution? 
I really don't know much about cmake, and I've already tried to come in and still can't solve it.

**The full error report in cmake is shown below:**
`"D:\CLion 2024.1.4\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Release "-DCMAKE_MAKE_PROGRAM=D:/CLion 2024.1.4/bin/ninja/win/x64/ninja.exe" -G Ninja -S D:\Projects\FEBioStudiotest\FEBioStudio-develop -B D:\Projects\FEBioStudiotest\FEBioStudio-develop\cmake-build-release
-- The C compiler identification is GNU 13.1.0
-- The CXX compiler identification is GNU 13.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/CLion 2024.1.4/bin/mingw/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/CLion 2024.1.4/bin/mingw/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at FindDependencies.cmake:22:
  Syntax Warning in cmake code at column 63

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:94 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR) 
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR) 
--     model ON
-- Found OpenGL: opengl32   
CMake Error at D:/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GLEW (missing: GLEW_LIBRARIES) (found version "2.2.0")
Call Stack (most recent call first):
  D:/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  D:/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/FindGLEW.cmake:242 (find_package_handle_standard_args)
  FindDependencies.cmake:638 (find_package)
  CMakeLists.txt:94 (include)

-- Configuring incomplete, errors occurred!

[Failed to reload]
`

**Comment by dollPrincess** [comment]
the error is this paragram:
`-- Found OpenGL: opengl32
CMake Error at D:/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find GLEW (missing: GLEW_LIBRARIES) (found version "2.2.0")`

**Comment by dollPrincess** [comment]
I know the whole error report seems long. But this situation is truely something that I connot solve, and I dont; know the reason. Please help me with it

**Comment by dollPrincess** [comment]
Okay, I figured it out.

**Comment by michaelrossherron** [comment]
I apologize that we weren't able to respond to you before you were able to figure out the problem yourself, but I'm glad that you were able to resolve the issue. 

Perhaps you could respond to this thread with the solution that you found so that if another user experiences the same issue, they will be able to follow the same steps as you?

Michael Herron

**Comment by dollPrincess** [comment]
> I apologize that we weren't able to respond to you before you were able to figure out the problem yourself, but I'm glad that you were able to resolve the issue.
> 
> Perhaps you could respond to this thread with the solution that you found so that if another user experiences the same issue, they will be able to follow the same steps as you?
> 
> Michael Herron

Hhhhh.
I am glad to see your saying like that. Sure. I have received your great help with patience before.

Anyway, after I open a new project in clion, the toolchain is mingw instead of vs. That's where the story begins, you need to click settings on the right top corner, and make sure your toolchain uses vs by default.
