### ISSUE TITLE
Bug Report | xplt compression

### ISSUE THREAD

**Issue by garraGH** [febiosoftware/FEBioStudio#124]
I save a xplt file with "data compression" checked，then i reload the compressed xplt，and read zero timestep.
I dig into the source code, seems that it doesn't actually compress the chunk data but only write out the compression flag when export the xplt file. But when you read the compression flag, you did decompress the chunk，so you failed to get the right data.
![image](https://github.com/user-attachments/assets/44962441-2833-4413-8f98-2fd14d9d0d97)

**Comment by garraGH** [comment]
version：2.7.0

**Comment by michaelrossherron** [comment]
It took me some time but I was finally able to reproduce this bug on my end. It looks like if FEBio is compiled without zlib, it still sets the compression flag in the plot file, but it can't actually compress the data. This results in an uncompressed plot file being written that has the compression flag set, and so when FEBio Studio reads it, it tries to decompress the uncompressed data and this prevents the file from being read correctly. We'll update the code to ensure that the compression flag isn't being set when FEBio isn't compiled with zlib, and that should prevent this in the future. 

That being said, I'm not sure how you ran into this bug, unless you're compiling the software itself. Is that what you're doing? If so, you'll want to make sure that you have zlib installed on your build machine, and that the USE_ZLIB flag in CMake is on. 

If you're not compiling it yourself, then please update to the latest version of the software, either by downloading a new installer from our website, or by using the Auto-updater. I think that this problem should go away once you do that. 

Please let me know if you have any more questions. 

Michael Herron

**Comment by garraGH** [comment]
Thanks. 
Both the version downloaded from your website or compiled by myself with USE_ZLIB flag does not work correctly.
I'll try the newest 2.8.1 version.

**Comment by garraGH** [comment]
oops, the same.
![image](https://github.com/user-attachments/assets/3a973af8-2a40-4d1b-9623-a5c5a1107b79)

**Comment by michaelrossherron** [comment]
Okay, I know what's happening now. There are two ways to create a compressed plot file. The first, and much more common approach is to add the <compression>1</compression> flag to the <plotfile> section of your feb file. This will result in FEBio writing a compressed version of the plot file as it's running the analysis. This is what I thought that you were doing. 

The second method is to do what you're actually doing: open a plot file in FEBio Studio, then save it after checking the _Data compression_ check box. This method of compressing the plot file is indeed broken. This feature is almost never used, and so it's likely been broken for some time, and we've just never noticed it. Now that we're aware of it, we'll get it fixed. For now, if you want a compressed plot file, you'll need to add that flag to the feb file manually, and then run it through FEBio which will then directly create a compressed file.
