### ISSUE TITLE
ERROR in reading 3d slicer .vtk file (using TetGen as meshing method)

### ISSUE THREAD

**Issue by Farhanuzzaman** [febiosoftware/FEBioStudio#16]
When I import the geometry from 3d slicer it worked for meshing method cleaver but not with TetGen in FeBIO Studio.
Saying:
Failed reading file:
C:/Users/CG-DTE/Documents/NewFolder/Model.vtk
ERROR: Only float data type is supported for POINT section.
How to sovle this problem. What I am doing wrong?

**Comment by gateshian** [comment]
Please attach a sample file that we can test.

**Comment by SteveMaas1978** [comment]
Support was added for double data type in POINT section.
