### ISSUE TITLE
type=”math” attribute to the parameter’s definition

### ISSUE THREAD

**Issue by ashkanalmasi** [febiosoftware/FEBioStudio#25]
Hello,

The type=”math” attribute works for E but it makes an error for phi0 (in biphasic). I am wondering to know what's the reason for that since they are both model parameter.

Please see the attached zip file.

Case_A.feb which is type=”math” for E. It works properly.
Case_B.feb which is type=”math” for phi0. I had an error.
> tag "phi0" (line 35) : invalid attribute "type"

Thanks!

[files.zip](https://github.com/febiosoftware/FEBioStudio/files/5680127/files.zip)

**Comment by gateshian** [comment]
This enhancement has now been implemented in the 'develop' branch of FEBio.

Please note that this issue should have been created in febiosoftware/FEBio.
