### ISSUE TITLE
Tet Remesh fails with attached geometry

### ISSUE THREAD

**Issue by gateshian** [febiosoftware/FEBioStudio#26]
See attached file.  After loading the file CouponRefined, select the part then Mesh->Tet Remesh, with Element size: 0.25, Min element size: 0.1, click on Apply, FEBioStudio crashes.

The model was imported as a Step file (Coupon.step), meshed using NetGen with Max element size: 0.25 (Coupon.fsm), then the mesh was refined locally by selecting elements around the fillets and using TetGen, with Element size: 0.1, and saved as CouponRefined.fsm.
[Archive.zip](https://github.com/febiosoftware/FEBioStudio/files/5683397/Archive.zip)

**Comment by SteveMaas1978** [comment]
For some reason the edge data returned by MMG does not appear to be consistent with original mesh, which causes a crash when FEBioStudio tries to update the geometry's edge data. Not sure if there is a better solution, but I now force the rebuild of the edge data after MMG.
