### ISSUE TITLE
Scaling parts by a factor of 1000 causes clipping when zooming in

### ISSUE THREAD

**Issue by gateshian** [febiosoftware/FEBioStudio#28]
Currently, the default length unit when importing a STEP file is mm.  If one imports a STEP part and scales it down by a factor of 1000 to convert length units to meters, zooming on the part causes clipping.  The only way to restore proper zooming behavior is to quit FEBioStudio, restart it and reload the file with the scaled part.  See attached example file.
[car-roadway.STEP.zip](https://github.com/febiosoftware/FEBioStudio/files/5921405/car-roadway.STEP.zip)

**Comment by SteveMaas1978** [comment]
This issue should now be fixed.
