### ISSUE TITLE
Cannot use atan2 in curve editor

### ISSUE THREAD

**Issue by boyleco** [febiosoftware/FEBioStudio#42]
atan2 function does not work in the function dialog of curve editor on FEBioStudio.
e.g. f(t) = atan2(1,5) should return a constant of 0.19739555984988075
but zero is plotted in the curve editor.
atan2() can be added to the loadcurve in the .feb file without issues.

**Comment by SteveMaas1978** [comment]
Support for the atan2 function was added.
