### ISSUE TITLE
Failure opening .feb files that contain "-" in the file name as a model

### ISSUE THREAD

**Issue by svizec** [febiosoftware/FEBioStudio#44]
As the title suggests. The exact same *.feb file was tested. When it contained "-", the file could not be opened (Failed reading/opening file). Later I converted "-" to "_" in the file name and it worked with no issues. 
[el_tet4_copy.txt](https://github.com/febiosoftware/FEBioStudio/files/7956832/el_tet4_copy.txt)

**Comment by michaelrossherron** [comment]
I wasn't able to reproduce this issue in either FEBio or FEBio Studio on Windows or Linux. The file that you sent, however, did have a problem. You had manually given the name "tetraeder domain" to the _SolidDomain_ element on line 61, but the solid domain names must match the names of the _Element_ elements in the _Mesh_ section. By renaming the solid domain to "tetraeder", I was able to get this model to run. I'm attaching the modified version of the file [here](https://github.com/febiosoftware/FEBioStudio/files/8235138/el_tet4_copy.txt)

If you're still running into your original issue, please respond with more information about the problem, including which operating system you're using, which version of FEBio or FEBio Studio you're running, and the exact steps that you take to reproduce the issue. 

Thank you.

Michael Herron

**Comment by SteveMaas1978** [comment]
I think this issue is fixed so closing now.
