### ISSUE TITLE
 Cannot type a mathematical expression for material parameters in prescribed uniaxial active contraction within an uncoupled solid mixture.

### ISSUE THREAD

**Issue by drdickerson** [febiosoftware/FEBioStudio#47]
While the feature exists for coupled solid mixture, it would also be useful for uncoupled solid mixtures.

**Comment by SteveMaas1978** [comment]
Looks like this is now possible with the latest version of FEBio Studio (2.7). Closing issue now, but let us know if you continue to have problems. 

Best,

Steve
