### ISSUE TITLE
If Preview is left on the Edit tab then Mesh toolbar is not available in PostView

### ISSUE THREAD

**Issue by modenaxe** [febiosoftware/FEBioStudio#49]
If the Build window is left on the _Edit_ tab in Preview, then there will be no mesh selection toolbar available in the PostView environment.
I assume this is a bug of the GUI, since it happens only with the Edit tab, and not with _Create_, _Mesh_ or _Tools_.
Cheers,
Luca
![image](https://user-images.githubusercontent.com/7674529/195504108-552dd1e0-9baf-45f1-8a6c-e079942b5203.png)

**Comment by SteveMaas1978** [comment]
Thanks for catching this. This has been fixed (in febiostudio2 branch).

**Comment by modenaxe** [comment]
thank you!
