### ISSUE TITLE
FEBio Studio 2 crashes when reading medical images

### ISSUE THREAD

**Issue by modenaxe** [febiosoftware/FEBioStudio#52]
Hello, I was very curious to check the new DICOM importer, but in my installation when I try to use it FEBioStudio crashes.
The issue is reproducible using the DICOM data available at the [BoneMat website](http://www.bonemat.org/downloads.html) (a software used for mapping material properties from CT scans to finite element models)  under the section Test Data. The test data are provided as a zip file and the DICOM images are in the "Realistic" folder data.
I also tried importing a [nrrd CT scan](https://github.com/araex/mitk-gem-site/tree/gh-pages/tutorial_files) from the [MITK-GEM website](https://araex.github.io/mitk-gem-site/) with the same results, unfortunately.
Cheers,
Luca

**Comment by SteveMaas1978** [comment]
Hi, we are aware of this problem. Apparently, ITK which we used for those readers had a secret dependency on a java module that we were unaware of.  As a result, febio studio is crashing trying to call those java dependencies, which we did not pack in the installers. We are currently trying to find a solution for this issue and hope to have this fixed in the next release (FEBioStudio 2.1). We apologize for this inconvenience. 

Steve

**Comment by modenaxe** [comment]
thank you for letting me know, I am looking forward to version 2.1 then!

**Comment by modenaxe** [comment]
@SteveMaas1978 I have a related question, mostly out of curiosity and I hope it's not out of scope here. I have seen that you are using SimpleITK, do you think that it would be possible, in the FEBio framework, to use MITK plugins? That would make available several algorithms from packages like MITK-GEM that have specific implementations for bone material properties mapping using medical images, e.g. [these plugins](https://github.com/araex/mitk-gem/tree/master/Plugins). Just a thought that I wanted to investigate...

**Comment by modenaxe** [comment]
@SteveMaas1978 just adding some updated considerations about the image import feature.

FEBioStudio 2.1 reads the DICOM files but the space between slices seems incorrect (again tested using the DICOM data available at the [BoneMat website](http://www.bonemat.org/downloads.html)). This is how the DICOM sequence is imported in FEBio:
![image](https://user-images.githubusercontent.com/7674529/228691008-7fa91e97-af79-48df-9343-cfbf6e0c2e41.png)

but this is how it actually should be (based on Bonemat DICOM viewer):
![image](https://user-images.githubusercontent.com/7674529/228691196-f60822ea-9069-42ab-8e36-097962f63342.png)

The images and the segmented models visible withing the images are the same.

**Comment by SteveMaas1978** [comment]
Thanks for this feedback. We'll look into it. 

Steve

**Comment by michaelrossherron** [comment]
Thanks for finding this issue! This was indeed a bug in our image reader, and I just fixed the problem. I was able to read in that BoneMat example correctly after the fix. 

We will likely not be doing another release for some time, but you can get access to this bug fix if you update to the latest development version by following the instructions in [this link](https://febio.org/knowledgebase/getting-started/updating-febio-and-febio-studio/#articleTOC_1). 

However, this fix won't be available until after our nightly builds run, and so you'll have to wait until tomorrow (4/6/23) to update and get this fix.

Let me know if you run into any further issues. 

Michael Herron

**Comment by modenaxe** [comment]
thank you @michaelrossherron , I will do some further testing and confirm if it works on a couple of datasets at least.
Luca
