### ISSUE TITLE
If Preview is left on the Edit tab then "Select Elements" and "Select Faces" on the Mesh toolbar are not functional in PostView

### ISSUE THREAD

**Issue by modenaxe** [febiosoftware/FEBioStudio#53]
Hello,
I was testing FEBio Studio 2 and I have found that Issue #49 that I have previously reported was solved but only partially, as the Mesh toolbar is now available but elements and faces cannot be selected from the model. Edges and nodes can be selected. I tested it using the simple model available in the repository under the "Mesh Convergence Tutorial" project.
Thank you,
Luca

**Comment by SteveMaas1978** [comment]
Thanks for catching this. I think I have it fixed now (for real this time :) ). Please do a [dev update](https://febio.org/knowledgebase/getting-started/updating-febio-and-febio-studio/) and then give it another try. Let me know what you find! 

Steve

**Comment by modenaxe** [comment]
Hi Steve the issue seems to be solved indeed, thank you for fixing it so quickly!
