### ISSUE TITLE
Crashing when running any model in Test Suite

### ISSUE THREAD

**Issue by jrichardson97** [febiosoftware/FEBioStudio#58]
Downloaded FEBio Studio 2 version 2.0 and 2.0.1. Trying to run any of the test suite models. causes the program to crash with the following error message. Examples work fine on 1.9 for me.  

![image](https://user-images.githubusercontent.com/29694877/215651496-75c2e106-2ec5-4105-bc05-aad53090ab34.png)

**Comment by SteveMaas1978** [comment]
Hi,

This error message looks like it's coming from the installer. Can you run FEBioStudio itself (not from the installer)? E.g., by double-clicking the executable in the installed bin folder. 

Thanks,

Steve

**Comment by jrichardson97** [comment]
The error seems to have fixed itself. It was occurring after downloading FEBioStudio2 and trying to run one of the Test Suite models. When loading a model, I would get a warning like shown in the image. When I tried running the solver, FEBioStudio2 would crash and give me the previously posted error message. Not sure what fixed this issue, but since receiving the error, I've both installed FEBioStudio 1.9 and run some additional models created by hand and downloaded from the forum so it may be something wrong with the initial install. 

![image](https://user-images.githubusercontent.com/29694877/216411009-cc5b5fe7-fa96-4b73-8ad1-73256a45debb.png)
