### ISSUE TITLE
heat and chem plugins fail to load after studio2/febio4 install

### ISSUE THREAD

**Issue by areaboater** [febiosoftware/FEBioStudio#59]
After installing studio2.0.1 and FEBio4, launching FEBio returns error "failed loading plugins FEBioHeat and FEBioChem invalid SDK version"

During installation, I ticked the box to "install SDK"

![image](https://user-images.githubusercontent.com/7034202/215865156-fde0b22d-cb32-4422-b0d4-f98a061cace6.png)

**Comment by SteveMaas1978** [comment]
This should be fixed in the latest version of FEBio and FEBio Studio. Closing issue but let us know if this is still a problem.

Best,

Steve
