### ISSUE TITLE
The load curve is not automatically defined when a load is applied in FEBio 2

### ISSUE THREAD

**Issue by Federico-Guidolin** [febiosoftware/FEBioStudio#61]
In FEBio 2.0 when you define a load you have to create a load curve associated with it in the curve editor.
In previous versions, this was done automatically by associating a linear load curve as default.
I don't know if this is intended or if it's a bug because if I define a prescribed displacement as a boundary condition, a load controller is automatically added in the model viewer.
Thank you for your attention to this matter.
Federico

**Comment by SteveMaas1978** [comment]
A default load controller should be attached to loads as well. For what particular load are you experiencing this issue? 

Thanks,

Steve

**Comment by Federico-Guidolin** [comment]
I experience this issue with both "Add nodal load > Nodal load" and "Add surface load > Force", if I define one of these loads the load controllers remain empty and if I run the simulation the solution diverges at time 0.3. But if I define a load curve for the load (in curve editor for example or directly by adding a new load controller), I don't experience the problem anymore.

**Comment by modenaxe** [comment]
Hello @SteveMaas1978 and @Federico-Guidolin, I have noticed the same behaviour in FEBio Studio for force-controlled simulations. For example, if you create a simple model like the one used in the [convergence study](https://febio.org/knowledgebase/tutorials/performing-a-mesh-convergence-study/performing-a-mesh-convergence-study) (simple rectangular beam blocked on one side with a nodal force applied to the free end), and define just a nodal force, without __manually__ defining a load controller, the model will not converge and no Load Controller is created by default either.

The _LoadData_ field, where I would normally find the definition of the Load controller, is also missing from the .feb file.


See images below:

![image](https://user-images.githubusercontent.com/7674529/234442946-6ae0bcd5-3138-4dcd-a8bb-68b4696b6277.png)



![image](https://user-images.githubusercontent.com/7674529/234443463-7424a426-d5cc-49b4-b7d4-3746af08f37a.png)


Cheers,

Luca

**Comment by SteveMaas1978** [comment]
Hi @Federico-Guidolin and @modenaxe,

It looks like indeed febio studio was not assigning default load curves to those loads. I have that fixed now, so please do a dev update tomorrow and give it another try. Let me know what you find.

Thanks,

Steve

**Comment by modenaxe** [comment]
Fantastic, thank you!

**Comment by modenaxe** [comment]
Now it works, thank you!
Luca
