### ISSUE TITLE
FEbio Repository Panel missing

### ISSUE THREAD

**Issue by danielchang46** [febiosoftware/FEBioStudio#62]
Hi,

The FEbio Repository is missing from my computer. I still have some of the files under documents -> FEBio Studio Repo files but not all of them, specifically "Webinar Contact Modeling 2." How can I get this back?  

![Repository Panel Missing](https://user-images.githubusercontent.com/126730916/222293309-6733db25-1002-4cef-8191-11e70196fa36.png)

**Comment by michaelrossherron** [comment]
It may be that the Repository panel is simply hidden at the moment. You can re-enable it by going to the _View -> Windows_ in the main menu, and then making sure that the _Repository_ option is checked. 

Please let us know if that fixes your problem. 

Michael Herron

**Comment by SteveMaas1978** [comment]
Haven't heard back from OP, so assuming all is working well :). Closing issue.
