### ISSUE TITLE
FEBio crashes whenever I try to run a simulation

### ISSUE THREAD

**Issue by kewe7879** [febiosoftware/FEBioStudio#64]
I am trying to find the stresses on a spider's exoskeleton when it moves through different compression conditions. Currently, I am working on the 40%. I am putting in prescribed displacements in the nodal boundary conditions. One boundary condition is the prescribed displacement of the legs on the left, the second is the prescribed displacement on the right. I also have a body force. I also created walls in the simulation at the 40% point on the spider's legs (where the legs would be displaced to) and had a contact interference between the legs and the walls. The walls had a solid material and the spider exoskeleton is natural neo-Hookean. I have the most updated version of FEBio. My issue is that, regardless of if I run it on my Surface 7 Pro with literally nothing else open or my lab's computer (that regularly does machine learning without issue) running on GPU with nothing else running, it crashes, and the files don't reload correctly (i.e. it loads a box instead of a meshed spider, or the file has 0 kb of information). Does anyone have an idea of how to prevent this?

**Comment by SteveMaas1978** [comment]
Is it possible to share the model file (fs2 or feb). I'll see if I can reproduce the issue. 

Thanks,

Steve

**Comment by SteveMaas1978** [comment]
Hi, can you please let us know if this is still an issue? Thanks!

Steve
