### ISSUE TITLE
FEBioStudio2 Crash when attempting to edit XML

### ISSUE THREAD

**Issue by Brandon-Swim** [febiosoftware/FEBioStudio#66]
I have generated the attached .feb file from a .fs2 file becuase it was giving me a weird error:

tag "rb" (line 1126) : invalid value: (invalid)       

when trying to run the file. However, whenever I try to open the .feb file as an XML, FEBioStudio crashes. 

[simplified_model_v2.txt](https://github.com/febiosoftware/FEBioStudio/files/11332825/simplified_model_v2.txt)

edit:
Just to clarifty, I know why it was throwing the error, I just wanted to post a bug report on the entire program crashing upon attempting to edit a .feb file as a .xml file.

**Comment by SteveMaas1978** [comment]
I think this might be fixed, or at least I can't reproduce this. Can you try updating to the latest [dev versio](https://febio.org/knowledgebase/getting-started/updating-febio-and-febio-studio/)n and give it another try? Let me know what you find. 

Thanks,

Steve
