### ISSUE TITLE
Select Range tool does not open in FEBio Studio 2.1.2

### ISSUE THREAD

**Issue by modenaxe** [febiosoftware/FEBioStudio#68]
Hello,
when I click Edit>Select Range from the menu, nothing happens and the tool does not open in FEBioStudio 2.1.2.
![image](https://user-images.githubusercontent.com/7674529/235462319-44be089a-d95b-4846-b718-f39acb6c036c.png)

Cheers,
Luca

**Comment by SteveMaas1978** [comment]
Hi Luca,

That menu option is only used on the post side. To address this I have separated the edit menu for the build and the post side. Take a look after tomorrow's dev update and give it a try. 

Thanks,

Steve
