### ISSUE TITLE
Named Selections doesn't update after changing the selected surface

### ISSUE THREAD

**Issue by BabakNSafa** [febiosoftware/FEBioStudio#70]
When editing a selected group of surfaces, the named selection appears not to get updated. FEBio throws out this error.

A surface with name "[$SURFACE]" was already defined. (line XXX) 

FEBio Studio v 2.2.0.156ebcf61

**Comment by SteveMaas1978** [comment]
I can't seem to find any problem with editing named selections. Can you please let us know if this is still an issue? If so, can you please provide a bit more detail? 

Thanks,

Steve

**Comment by BabakNSafa** [comment]
Sorry for the delayed response. It seems that the issue has been resolved in later stable releases.

Best,
Babak
