### ISSUE TITLE
Physics module resets with geometry import

### ISSUE THREAD

**Issue by smithjh-lafayette** [febiosoftware/FEBioStudio#72]
I think that I have found a bug in FEBio Studio 2.2 that seems to have a trivial workaround but is having consequences for us:

1. Create a new model and choose anything other than "Structural Mechanics", such as "Fluid-Structure Interaction."
2. Import a geometry.
3. The model will revert to a structural mechanics analysis, showing "Model [solid]".  The material models "Biphasic-FSI" and "Fluid-FSI" will not be available.

The workaround is to choose "Physics > Edit Physics Module > fluid-FSI."  The model will still show "Model [solid]", but the material models "Biphasic-FSI" and "Fluid-FSI" will now be available.  Once you choose one of them, the model will change to "Model [fluid-FSI]".

The problem we have is that we would like to replace the mesh of an existing simulation.  When we try to do so, FEBio Studio crashes.  We are thinking that this may be because the Fluid-FSI material in our simulation is not compatible with the structural mechanics physics that the program reverts to.

Thanks,
Josh

**Comment by SteveMaas1978** [comment]
Hi Josh,

I can't reproduce this issue, so I think it has been resolved at some point. 
Let us know if this is still happening for you. 

Thanks,

Steve
