### ISSUE TITLE
boundary condition on Parts error in v 2.3.0

### ISSUE THREAD

**Issue by BabakNSafa** [febiosoftware/FEBioStudio#73]
Assigning a boundary condition (e.g., Fixed Displacement) to the entire Part doesn't set the a name. 
Error example
```
*************************************************************************
 *                                ERROR                                  *
 * tag "bc" (line 174) : invalid value for attribute "node_set"          *
 *************************************************************************

```
![image](https://github.com/febiosoftware/FEBioStudio/assets/35350283/0b029625-c7e2-4b42-80a9-662501cbcbaa)

Example file below. I renamed the .feb file to .txt so I can upload it here.
[Model1.txt](https://github.com/febiosoftware/FEBioStudio/files/12588712/Model1.txt)

**Comment by SteveMaas1978** [comment]
Sorry for the belated reply, but I just tried this with the latest version (2.7) and don't see this issue. I'm going to assume this is fixed. I'm closing this issue now but let us know if this issue is still present in the latest version. 

Thanks,

Steve
