### ISSUE TITLE
[feature request] choosing what version auto update install

### ISSUE THREAD

**Issue by BabakNSafa** [febiosoftware/FEBioStudio#74]
Since sometimes the new features are not retroactively compatible, or change the workflow, it would be useful to add an option in Help--> Check for Updates.. to choose what version is installed. Sometimes it is useful to install older versions.

**Comment by michaelrossherron** [comment]
This is something that I've considered doing in the past, but unfortunately, it would require a near-complete rewrite of our auto-updater, both client- and server-side. We do not store old copies of the binaries on our auto-update server. We only store a copy of the latest versions of all of our files. 

We do, however, keep an archive of all of our old installers. If you go to the [FEBio Studio download page](https://febio.org/downloads/), login, and scroll down to your OS, you should see a link labeled _Previous versions_. Clicking on that link will show you download links for all versions of the software going back to version 1.0. You can download whichever version you'd like, uninstall your current version, and then install the old one instead. 

All of that being said, while we cannot always guarantee backward compatibility, we do try our best to prevent breaking that compatibility. If there are specific changes that we've made that have broken compatibility, please make another post about them, and we can see if we can fix the issue. If the change is workflow-related, then we may not be able to do anything about it, but if a change is preventing older files from running, or being read, then we'd very much like to hear about it. 

Michael Herron

**Comment by michaelrossherron** [comment]
This is something that I've considered doing in the past, but unfortunately, it would require a near-complete rewrite of our auto-updater, both client- and server-side. We do not store old copies of the binaries on our auto-update server. We only store a copy of the latest versions of all of our files.

We do, however, keep an archive of all of our old installers. If you go to the [FEBio Studio download page](https://febio.org/downloads/), login, and scroll down to your OS, you should see a link labeled Previous versions. Clicking on that link will show you download links for all versions of the software going back to version 1.0. You can download whichever version you'd like, uninstall your current version, and then install the old one instead.

All of that being said, while we cannot always guarantee backward compatibility, we do try our best to prevent breaking that compatibility. If there are specific changes that we've made that have broken compatibility, please make another post about them, and we can see if we can fix the issue. If the change is workflow-related, then we may not be able to do anything about it, but if a change is preventing older files from running, or being read, then we'd very much like to hear about it.

Michael Herron

**Comment by michaelrossherron** [comment]
This is something that I've considered doing in the past, but unfortunately, it would require a near-complete rewrite of our auto-updater, both client- and server-side. We do not store old copies of the binaries on our auto-update server. We only store a copy of the latest versions of all of our files.

We do, however, keep an archive of all of our old installers. If you go to the [FEBio Studio download page](https://febio.org/downloads/), login, and scroll down to your OS, you should see a link labeled Previous versions. Clicking on that link will show you download links for all versions of the software going back to version 1.0. You can download whichever version you'd like, uninstall your current version, and then install the old one instead.

All of that being said, while we cannot always guarantee backward compatibility, we do try our best to prevent breaking that compatibility. If there are specific changes that we've made that have broken compatibility, please make another post about them, and we can see if we can fix the issue. If the change is workflow-related, then we may not be able to do anything about it, but if a change is preventing older files from running, or being read, then we'd very much like to hear about it.

Michael Herron
