### ISSUE TITLE
FEBio Studio crashes on Mac when "Auto time stepper" is set to remove

### ISSUE THREAD

**Issue by modenaxe** [febiosoftware/FEBioStudio#75]
Hello,

FEBio Studio 2.2 crashes instantaneously on Mac when "Auto time stepper" is set to remove, e.g. because we want to personalise time steps and step size.

Best regards,

Luca

**Comment by SteveMaas1978** [comment]
Hi Luca, 

Sorry for the belated reply, but I can't reproduce this. I'm assuming this issue has been fixed. Closing this now but let us know if this is still a problem.

Best,

Steve

**Comment by modenaxe** [comment]
Hi @SteveMaas1978 we are still experiencing this crashes also in FEBio Studio 2.7 - I will upload a screen capture video as soon as possible, but in the meanwhile I would like to reopen the issue.
