### ISSUE TITLE
Creating Force Load and Copying a load does not create a Loading Controller

### ISSUE THREAD

**Issue by modenaxe** [febiosoftware/FEBioStudio#76]
I have noticed that when defining a nodal load of type Force, (e.g.  Loads>Add Surface Load>Force via the menus) a force is created in the Model Viewer but there is no Load Controller automatically created/associated with it.

Similarly issue in this case: if I create a Nodal Force (Loads>Add Nodal Load>Nodal Force via the menus) a nodal force is created. If then I want to copy this nodal force (right click on the item and select "Copy"), the nodal force is correctly created but no Load Controller is created/associated with it.

I found this but on FEBio Studio 2.2 (using it for teaching) but on the release note I have seen that they are not mentioned so I assume they are still there also in v 2.3.

**Comment by SteveMaas1978** [comment]
The next release (fbs 2.7) will add a default load curve to the surface force load. 
I can't reproduce the other issue, though. I suspect that has already been fixed in a previous version.

**Comment by modenaxe** [comment]
Ok, thank you. If I notice anything weird I will report back or reopen the issue.
