### ISSUE TITLE
Cylindrical Fiber Definition Rotation at Thinner Region of Part

### ISSUE THREAD

**Issue by cnb2376** [febiosoftware/FEBioStudio#78]
I'm defining a cylindrical coordinate system for a spinal disc annulus material model so that I can have fibers crossing one another at a set orientation.

I'm seeing expected direction for the fibers throughout the object, with {0,1,0} wrapping around the annulus, except near the thinner region of the annulus, where the fibers start to rotate vertically.

I've attached images, I created an object to mark where I've labeled the center, and the axis has a value of {-.12,0,-.99}, since the annulus is slightly rotated in the x-direction.

I'm unsure if this behavior is occurring due to improperly defined center / axis, or if it's likely to stem from the part mesh.

Open to sharing the .fs2 file for troubleshooting, file type was not supported for upload in this post.

![Annulus_Top_View](https://github.com/febiosoftware/FEBioStudio/assets/89807214/5ec654a6-9dee-4dd8-b2c9-4d1579b4dd00)
![Annulus Side View](https://github.com/febiosoftware/FEBioStudio/assets/89807214/75f17e8f-de68-4f16-a984-1a0912d12c91)

**Comment by SteveMaas1978** [comment]
Thanks for bringing this to our attention. There was indeed an issue with the cylindrical fiber generator, but I think I have this fixed now. Please do a dev update tomorrow after the nightly builds and then give it another try. Let me know what you find.

**Comment by cnb2376** [comment]
The update helped tremendously, the problem with the fibers rotating at the thinner region is no longer present, and the cylindrical fibers wrap around the center / axis as expected.

​​​​​​​Thank you very much!
