### ISSUE TITLE
Missing Netgen libraries

### ISSUE THREAD

**Issue by AugustusGreenwood** [febiosoftware/FEBioStudio#83]
Building on Arch linux, CMake wants to find nglib, csg, interfac, occ and mesh(ing) libs. When I compile the newest version of netgen, however, it seems that csg, interface, occ and mesh(ing) libs aren't built, and netgen doesn't provide a direct way of building them. When I built just linking with nglib and ngcore, it compiles successfully and seems all mmg functionality is present and working. Maybe I missed something but it doesn't appear the other libs are required with newer netgen builds.

I noticed in another issue, you are re-hauling your build, is this something being implemented? If not, I could submit a pull request with the appropriate change to the CMakeLists file.

**Comment by gateshian** [comment]
Hi, try compiling on the netgen_update branch.  The CMakeLists file has been updated there, to only include ngcore and nglib.

**Comment by AugustusGreenwood** [comment]
Compiles great. My bad for missing that branch/commit updating CMakeLists.
